create table if not exists public.challenges (
    id bigint generated by default as identity primary key,
    tx_signature text not null unique,
    challenge_pda text not null unique,
    challenge_id bigint not null,
    creator_wallet text not null,
    market text not null default 'SOL-PERP',
    asset text not null,
    bet_amount_sol double precision not null check (bet_amount_sol > 0),
    target_price_usd_cents bigint not null check (target_price_usd_cents > 0),
    direction_above boolean not null,
    expires_at bigint not null,
    resolves_at bigint not null,
    status text not null default 'open' check (status in ('open', 'active', 'settled', 'cancelled')),
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    constraint challenges_resolves_after_expiry check (resolves_at > expires_at)
);

create index if not exists challenges_created_at_idx
    on public.challenges (created_at desc);

create index if not exists challenges_creator_wallet_idx
    on public.challenges (creator_wallet);

create index if not exists challenges_status_idx
    on public.challenges (status);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists set_challenges_updated_at on public.challenges;

create trigger set_challenges_updated_at
before update on public.challenges
for each row
execute function public.set_updated_at();
